### ISSUE TITLE
Are you looking after org-caldav?

### ISSUE THREAD

**Issue by mickael-kerjean** [grauschnabel/org-caldav#2]
Hello there,

First of all, congrats on your work. I've been using org-caldav for several months but I've seen quite a few issues with it and ended up stop using it. I've seen at that time you were and still are very active in the original repo but never seen any intervention from the original author.

Today I've received a request regarding supporting caldav in an orgmode companion app I'm looking after and it raises the question of what is happening with org-caldav. I've seen you created the very requested VTODO feature which awesome but as of today It hasn't been merge yet. Is it because the original author wouldn't answer or because the feature isn't ready?

That's the link to the original issue that was created from another [org user](https://github.com/mickael-kerjean/nuage/issues/66)

**Comment by grauschnabel** [comment]
Hi there,
I'm not sure, why it isn't merged.  I think it is because I changed some whitespaces, to make it figure better here, and dengste could not check what I changed, and I changed a lot, but always trying not to touch the original version even not to change its default behaviour (so vtodo is not synced by default).
I still have some issues here I think, because I just tested it for my own setup (nextcloud sync).
But if you use it and report the issues here, it will work someday. :)
I still havent merged the last version of dengste, because it had some issues.

You could help me testing and trying, so we get it great. :)  I use this repo quite a while on real production calendars (about 4 calendars), but using git to make sure I don't loose any data.

- Martin

**Comment by mickael-kerjean** [comment]
> You could help me testing and trying, so we get it great.

I'm all in. A proper dav integration would completly change my interaction with org mode. I'd love to use org caldav but during my initial test, I've experienced many issues I had no idea if it was due to a problem in the configuration or package.

FYI, my dav server is Radicale

**Comment by mickael-kerjean** [comment]
I'll try to find the config I had for it and switch my version to yours and keep you update

**Comment by grauschnabel** [comment]
I don't know Radicale, but on the website it says, the whole iCal standard is supported. That's great, so we get it working. :)

**Comment by TRSx80** [comment]
I was also curious about the subject. Are you in touch with dengste?

Seems like quite a lot of people using org-caldav and there are few improvements that could be made here and there.

I know that it is pretty critical to my workflow and changing over to doing everything in Emacs / Org.

**Comment by grauschnabel** [comment]
I'm not really in touch with dengste, even if I mostly checkout his repo, because its the original one.  I just wanted to make the TODOs working together with my android phone.  Thats why I made the fork.  I tried to merge his branch again but the last merge broke mine, so this is more alone.  I'd like to get the LOCATION working, but there was not enaugh time until now.

If you use org with caldav it might be a good way to use git too. :)

**Comment by TRSx80** [comment]
Yeah I am on dengste latest version and LOCATION does work for me and can enter on mobile or in Org and it works both ways. But perhaps that is what you meant by trying to merge again with his (I am still very new to git and learning terminology)?

**Comment by grauschnabel** [comment]
I made a fork of dengstes version.  There I could merge all the changes he made too.  But I commited with different whitespaces, so git is a bit wired.  I have to figure out how to deal with that.  So I can merge all new changes he has made here.

**Comment by whirm** [comment]
> I made a fork of dengstes version. There I could merge all the changes he made too. But I commited with different whitespaces, so git is a bit wired. I have to figure out how to deal with that. So I can merge all new changes he has made here.

Would you take maintainership over the project? I could work on a PR that fixes the whitespaces issue if that helped.

**Comment by grauschnabel** [comment]
Yes, I would like to  take over the maintainership. Would be great if you could fix the whitespace issue and maybe implement something that sets the indentation right?
Thanks for your help.

**Comment by whirm** [comment]
I'm quite busy this week but I'll try to squeeze some time to work on that.

Cheers!

**Comment by whirm** [comment]
This PR should be enough to get started. I'll try to find some time to look at other fork's changes and bring in stuff that looks interesting.

**Comment by whirm** [comment]
This last PR should allow you to bring in anything interesting other people made.

> Would be great if you could fix the whitespace issue and maybe implement something that sets the indentation right?

Everything should be fine from now on as long as you don't accept commits with tabs on it. Which no sane Emacs setup should add now that there's no tab/space mix.

**Comment by grauschnabel** [comment]
hi there, i'm missing a few fingers right now, so this has to wait until they are heal again.  its so hard for me not to use all fingers on the keyboard, i'm not patient enough...

**Comment by whirm** [comment]
Sure, take care of yourself!

**Comment by grauschnabel** [comment]
I merged your pull request.

**Comment by whirm** [comment]
I saw. I rebased #5. you can cherry pick what's interesting or I can drop whatever is not from it I don't mind either way.

**Comment by rohlik-hu** [comment]
Thanks a whole lot for your work, grauschnabel. I have been struggling for days with org-caldav syncing only events to calendars, but no VTODOs to tasks/reminders. Now it seems you have found the solution. Works greatly! My setup is a SoGo calendar server and the macosx Reminders app. I would definitely support merging your fork back into dengste/caldav.

**Comment by grauschnabel** [comment]
I have seen that is not stable here at the moment, so this needs to wait a while...

**Comment by TRSx80** [comment]
Happy to see some activity here finally! Thanks everyone for all your great work! :)

Hope your fingers getting better, @grauschnabel!

**Comment by kahironimashte** [comment]
As a non-programmer I wonder what is the dificulty in a sync from org to caldav? Where is the bottleneck?

Can I help with non-programming tasks somehow?

**Comment by grauschnabel** [comment]
I think [dengste/org-caldav](https://github.com/dengste/org-caldav) has updates again.
