### ISSUE TITLE
Read Only Calendars

### ISSUE THREAD

**Issue by Nebucatnetzer** [grauschnabel/org-caldav#3]
I hope you don't mind me asking this here since the original dev isn't so active anymore.
Is it possible to make a CalDav source read only?
Since org-caldav isn't really reliable at the moment I would prefer it, if it just reads the calendars so that I can view them in Emacs.
I've already configured it so that it never overwrites the caldav source and always overwrites the org file. However sometimes it still makes a put which messes with my recurring events.

**Comment by grauschnabel** [comment]
As far as I know, there is no way to do this.

However you could have one file like `my-google-calendar.org` which will be synced both ways, but you don't edit it locally.

But about your problem, there is a lack of support for recurring events.  Most users, as far as I know, use to have org-mode as higher priority than the remote calendar, like me, I use the remote only for adding new appointments on the fly, but the local org file for everything else.  Recurring events, even if possible with org-mode are made by `org-clone-subtree-with-time-shift`, so I can document every event separately.

Maybe someone could add real support for recurring events. ?

**Comment by Nebucatnetzer** [comment]
That's what I'm doing now but for some reason org-caldav still thinks that it has to upload them.
Maybe because it lost some information which is in the original entry?

**Comment by grauschnabel** [comment]
Do the remote added recurrent events show up correctly in org mode?
I would guess that org-caldav finds changes which aren't ever made.
If you could create an extra calandar and test it with one entry, you could help us to figure out whats happening?

**Comment by Nebucatnetzer** [comment]
The recurrent events don't show correctly in org mode. It only shows the
first event. Sure I can do that. It'ts probably anyway better for
testing than playing around with my productive calendars :D.

Should I just create a recurrent event in the calendar and see what
org-caldav changes it to?
Martin writes:

**Comment by Nebucatnetzer** [comment]
In the log I see some of these:

```
UID: Nextcloud-ZXPJHFNQFR430QHDO1CB1
   Title: (Could not find UID)
   Status: error  Action: error:inbox-notfound
   Calendar: test

```

And then when syncing it shows that it puts 25 events

```
Event UID c04e9710-dd0b-473d-a571-04e9d606e767: Org --> Cal
Putting event UID c04e9710-dd0b-473d-a571-04e9d606e767.
```

However none of these events are recurrent events.

**Comment by Nebucatnetzer** [comment]
Ah and sometimes I see this error

```
ID: Nextcloud-ZXPJHFNQFR430QHDO1CB1
   Title: (Could not find UID)
   Status: error  Action: error:inbox-notfound
   Calendar: test
```
and this one
`org-caldav-url-dav-get-properties: Wrong type argument: integer-or-marker-p, nil`

**Comment by grauschnabel** [comment]
Maybe you could post the whole config and org entry for that?  your test file?  So that i can reproduce it here. (I also use nextcloud, so I could try your setup.)  For me I prefer to have org-mode as first place, and I use git, so I can play arround on productive calendars and reset them if there was something wrong. :)
Best way could be if you tell me all the steps to reproduce your error.  I will make a fix then.

**Comment by Nebucatnetzer** [comment]
The config is no problem, I can send you the .org file directly if you have an email address. I would prefer not to post it here :)

```
(when (is-linux-p)
(use-package org-caldav
  :after org
  :ensure t
  :init
  (setq org-caldav-delete-org-entries 'alway)
  (setq org-caldav-delete-calendar-entries 'never)
  (setq org-caldav-url "https://mydomain.ch/remote.php/dav/calendars/andreas")
  (setq org-caldav-calendars
    '((:calendar-id "test"
       :files ("~/03_documents/org/personal/agenda/calendars/calendar.org")
       :inbox "~/03_documents/org/personal/agenda/calendars/calendar.org")))
  (setq org-icalendar-timezone "Europe/Zurich")))
```

I've used git for a while but it's a bit of a pain on Windows and syncing it to Android is easier with WebDav that's why I store all the org files in my Nextcloud.

**Comment by Nebucatnetzer** [comment]
Ah and for reproduction.
I just sync the calendar and save it in Emacs. But besides that I never do anything inside the org files.
For me it would be enough to see the entries and manage them from my phone or in the browser.

The only real editing which might occur could be that Emacs deletes some trailing white space when  saving.

Sometimes it works and sometimes it tells me that it puts some events or it shows the errors I've posted above.

1. org-caldav-sync
2. Save through org-agenda to save all the files at once
3. at a later point execute org-caldav-sync again

**Comment by grauschnabel** [comment]
Check my website for an email address...

**Comment by grauschnabel** [comment]
I didn't have time till now. if this is still open, i would spend some time on this, just tell me.

**Comment by Nebucatnetzer** [comment]
Thanks for the heads-up.
I'm currently working around this probem but if there would be a solution to implement caldav directly that would make org-mode a whole lot more usable.

**Comment by grauschnabel** [comment]
closed, because that is old.  See https://github.com/dengste/org-caldav instead.
